services:
  mongo: # Database
    container_name: mongodb
    networks:
      - finances-app-network
    image: mongo
    volumes:
      - ./db_data:/data/db
    restart: always # always restart the container even if it is manually stoped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    expose:
      - 1234:1234

  mongo-express: # Administration interface for MongoDB
    container_name: mongo-express
    networks:
      - finances-app-network
    image: mongo-express
    links:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  app:
    container_name: app
    networks:
      - finances-app-network
    build: .
    image: image-app
    volumes:
      - ./app:/app
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017/
    command: tail -F anything


networks:
  finances-app-network:
    name: finances-app-network